name: CI
on:
    push:
        branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  # TODO: Update in future to 16 + make workflow how to update this dependency
                  node-version: '14'

            - name: Install production dependencies
              run: npm install --no-fund --only=production

            - name: Install development dependencies
              run: npm install --no-fund --only=development

            - name: Build
              run: npm run build

            - name: Deploy on GitHub pages
              run: gh-pages -d ./build
